# Service Kubernetes config

apiVersion: v1
kind: Service
metadata:
  name: devops-webapp-service
  labels:
    app: devops-webapp
spec:
  selector:
    app: devops-webapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: NodePort
