#Docker Compose

services:
  server-health:
    build:
      context: ../system_info
      dockerfile: Dockerfile
    container_name: server_health
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-web
    ports:
      - "8080:80"
    restart: unless-stopped
